name: Scrape & Deploy Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install scraper deps
        working-directory: ./scraper
        run: |
          npm install --no-fund --no-audit
          npx playwright install --with-deps

      - name: Run scraper
        working-directory: ./scraper
        run: npm run scrape

      - name: Install web deps & build
        working-directory: ./web
        run: |
          npm install --no-fund --no-audit
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web/dist

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
